version: "3.9"
services:
  app:
    build: .
    # ports:
      # - "8080:8080"
    environment:
      PORT: 8080
      MONGODB_URI: "mongodb://mongo:27017/my-db"
      SECRET: "my-secret"
    depends_on:
      - mongo
  mongo:
    image: mongo
  mongo-express:
    image: mongo-express
    # ports:
      # - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
      ME_CONFIG_SITE_BASEURL: /db/
    depends_on:
      - mongo
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # nginx.conf has config for /db/ so it doesn't go to the node frontend and only to mongo express
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./server.crt:/etc/nginx/certs/server.crt
      - ./server.key:/etc/nginx/certs/server.key
    depends_on:
      - app
      - mongo-express