apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 1;

    events { worker_connections 1024; }

    http {
      sendfile on;

      upstream app-service {
        server app-service:80;  # Use the service name and port for HTTP
      }

      upstream mongo-express-service {
        server mongo-express-service:8081;  # Use the service name and port for HTTPS
      }

      server {
        listen 80;
        server_name localhost;
        location / {
            return 301 https://$host$request_uri;
        }
      }

      server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        location / {
          proxy_pass http://app-service;  # Use the upstream name defined above
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /db/ {
          proxy_pass http://mongo-express-service;  # Use the upstream name defined above
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
