apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      targetPort: 80
      port: 80
      nodePort: 30080 # this is the port that will be exposed to the outside world for http
    - name: https
      protocol: TCP
      targetPort: 443
      port: 443
      nodePort: 30443 # this is the port that will be exposed to the outside world for https
  type: NodePort